### ISSUE TITLE
Fallo al recuperar las claves de la base de datos

### ISSUE THREAD

**Issue by davmunmoy** [jeparca/EGCVerificacion15#11]
El cifrado y descifrado de un texto falla al conseguir las claves de la base de datos. 

El fallo se produce al ejecutar el método getPublicKey y getPrivateKey los resultados que se obtienen de estos métodos no permiten encriptar y desencriptar correctamente.

Habría que repasar la generación de claves y cómo se guardan en la base de datos.

**Comment by angontor** [comment]
Solucionado el problema al recuperar las claves de la base de datos. Se ha utilizado la libreria Commons-codec para realizar la conversion a y de Base64.
