### ISSUE TITLE
Fallo al decifrar voto cifrado, en el que el voto en claro era menor que 31 caracteres.

### ISSUE THREAD

**Issue by AlbertoGarciaSanchez** [jeparca/EGCVerificacion15#12]
- Cuando se recibe un voto cifrado, en el que el voto en claro era menor que 31 caracteres, el método citCifVote, devuelve un arrray vacío y por tanto el descifrado no tiene nada que descifrar y falla.
- Para reproducir la incidencia, se debe cifrar un texto menor de 31 caracteres de la votación cuyo id = 999999991. Después en el descifrado, introducimos ese texto cifrado, provocando el error.
- No devuelve ningún error, ya que no cifra nada.

**Comment by angontor** [comment]
Se ha incluido un else en el código para comtemplar la posibilidad cuando el tamaño es menor y asi se pueda descrifrar correctamente.
