### ISSUE TITLE
Problema visibilidad método calculateToken 

### ISSUE THREAD

**Issue by rafaeldrs** [jeparca/EGCVerificacion15#13]
Hay un problema detectado existente con el método calculateToken de verificación.

¿Qué se esperaba obtener? Se esperaba realizar una llamada a este método desde nuestro subsistema.

¿Qué se ha obtenido? El método es private por lo que no podemos acceder a él.

Solución: cambiar visibilidad del método de private a public (no protected).

**Comment by angontor** [comment]
Incidencia creada por un error en la comunicación.
El problema se soluciona copiando los métodos cuando se vaya a calcular el token.
