### ISSUE TITLE
Problema token de verificacion

### ISSUE THREAD

**Issue by rafaeldrs** [jeparca/EGCVerificacion15#14]
Hay un problema detectado existente con el método getPrivateKey de la clase AuthorityImpl de verificación.

¿Qué se esperaba obtener? Se esperaba realizar una llamada a este método desde nuestro subsistema para obtener la clave privada para descifrar

¿Qué se ha obtenido? El método devuelve por consola un error "java.sql.SQLException: No suitable driver found for jdbc:mysql://egc.jeparca.com:3306/jeparcac_egc", terminando con "El token no coincide en desencriptar"

**Comment by rafaeldrs** [comment]
Adjunto captura
![img-20151212-wa0010](https://cloud.githubusercontent.com/assets/12884748/11763282/3bf00010-a104-11e5-8b5c-b25fbeddd7cf.jpeg)

**Comment by rafaeldrs** [comment]
Adjunto imagen
![img-20151212-wa0010](https://cloud.githubusercontent.com/assets/12884748/11763286/51971df4-a104-11e5-9bec-520b83467f18.jpeg)

**Comment by jeparca** [comment]
Comunicado a la gestora de incidencias y el resto del equipo

**Comment by jeparca** [comment]
Parece problema de dependencias respecto al driver nativo para Java y MySQL

**Comment by jeparca** [comment]
Aunque se soluciona el problema de dependencias importando el JAR, a través de Maven sigue presentando fallos

**Comment by rafaeldrs** [comment]
Problema solucionado con la versión 2.0.5 del jar

**Comment by angontor** [comment]
Solucionado el problema con el método getPrivateKey en la llamada desde el subsistema de recuento.
