### ISSUE TITLE
Fallo de Jenkins al usarlo en Openshift

### ISSUE THREAD

**Issue by jeparca** [jeparca/EGCVerificacion15#15]
Descripción: Hay un fallo, principalmente en el uso de Java 8, ya que el servidor de Jenkins en Openshift no lo soporta y no se compila el proyecto.

Pasos: Intentar ejecutar la tarea de compilación

Error: Fallo al compilar. Error de la versión de Java (1.8)

Comentarios: se comienza a solucionar bajando de versión de Java

**Comment by angontor** [comment]
Se ha solucionado el problema cambiando la versión de Java a 1.7 y comprobamos que compila correctamente.
