### ISSUE TITLE
Problema codificación cifrado y descifrado

### ISSUE THREAD

**Issue by rafaeldrs** [jeparca/EGCVerificacion15#16]
Subsistema: Recuento
Descripción: Si se cifra un voto y posteriormente se descifran, aparecen caracteres extraños
![captura](https://cloud.githubusercontent.com/assets/12884748/11905807/a608a650-a5c8-11e5-86db-59eed727721b.png)
![captura2](https://cloud.githubusercontent.com/assets/12884748/11905833/dd9f9f9c-a5c8-11e5-8dc4-8672e3705071.png)

He enviado a Jesús un correo con la clase de Test con la que he sacado esas capturas. Simplemente añadidla a vuestro proyecto y ejecutar.

Un saludo y gracias.

**Comment by jeparca** [comment]
[MiTest.txt](https://github.com/jeparca/EGCVerificacion15/files/67109/MiTest.txt)

Renombrar a .JAVA

**Comment by jeparca** [comment]
Esta incidencia está siendo gestionada por el coordinador, con todos los miembros trabajando en ella y será él quien la cierre.

**Comment by jeparca** [comment]
Encontrado el problema, y procediendo a su solución

**Comment by jeparca** [comment]
La incidencia fue solucionada mediante el cambio del método de corte del voto, al detectarse que caracteres especiales como "ñ" o "¿" ocupan más de un byte y teniendo el límite en 31. Pasa a haber un límite de 15 caracteres por cada cadena cifrada. Además, ninguna cadena a cifrar puede empezar por un carácter especial. Esta incidencia fue solucionada el 17 de diciembre.
