### ISSUE TITLE
Formato claves públicas en base de datos modificado

### ISSUE THREAD

**Issue by AlbertoGarciaSanchez** [jeparca/EGCVerificacion15#7]
El método encrypt ha quedado afectado al modificar el formato en el que se guardan las claves públicas.
Antes se guardaban de la forma:
x: xxxxxx y: yyyyyy
Ahora se guardan directamente los números con un separador de "++++":
xxxxxx++++yyyyyy

**Comment by angontor** [comment]
Se ha solucionado el problema modificando el formato en el que se almacenaban las claves a un formato mas eficiente.
